# Generated by Django 4.0.6 on 2023-01-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_announcement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttonquestion',
            name='button',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='ButtonQuestion',
        ),
    ]
