# Generated by Django 4.0.6 on 2023-01-22 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoption_announcement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('dog', 'Pies'), ('cat', 'Kot'), ('rabbit', 'Królik'), ('snake', 'Wonsz'), ('other', 'Inne')], default='dog', max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Męska'), ('F', 'Żeńska'), ('O', 'Inna')], default='M', max_length=1)),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=100)),
                ('weight', models.FloatField(help_text='w kilogramach', max_length=10)),
                ('age', models.PositiveSmallIntegerField()),
                ('months', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('health_and_vaccination', models.TextField(default=' ', max_length=3000)),
                ('care', models.TextField(default=' ', max_length=3000)),
                ('past', models.TextField(default=' ', max_length=3000)),
                ('care_taker', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Announcment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('age', models.SmallIntegerField()),
                ('species', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=15)),
                ('health', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='buttonquestion',
            name='button',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='ButtonQuestion',
        ),
    ]
