# Generated by Django 4.0.6 on 2023-01-29 09:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoption_announcement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_education', models.CharField(max_length=250)),
                ('number_of_adults_in_the_house', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('number_of_children_in_the_house', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('other_animals', models.CharField(max_length=250)),
                ('hours_away_from_home', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('moving_out', models.CharField(max_length=250)),
                ('family_allergies', models.CharField(max_length=250)),
                ('adoption_reason', models.CharField(max_length=250)),
                ('animal_name', models.CharField(max_length=50)),
                ('availability', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('feeding_the_animal', models.CharField(max_length=250)),
                ('care_budget', models.CharField(max_length=150)),
                ('what_if_you_go_on_vacation', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Samiec', 'Samiec'), ('Samica', 'Samica'), ('Inna', 'Inna')], default='Inna', max_length=6)),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=100)),
                ('weight', models.FloatField(help_text='w kilogramach', max_length=10, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('age', models.PositiveSmallIntegerField()),
                ('months', models.PositiveSmallIntegerField(blank=True, default=0, help_text='fill when age is below 1 year', null=True, validators=[django.core.validators.MaxValueValidator(12)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('health_and_vaccination', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('care_taker', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='buttonquestion',
            name='button',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='age',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='health',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='name',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='species',
        ),
        migrations.AddField(
            model_name='announcement',
            name='added_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ButtonQuestion',
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption_announcement.animal'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='animal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='adoption_announcement.animal'),
            preserve_default=False,
        ),
    ]
