# Generated by Django 4.0.6 on 2023-01-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoption_announcement', '0002_remove_buttonquestion_button_delete_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
                ('age', models.SmallIntegerField()),
                ('species', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=15)),
                ('health', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
