# Generated by Django 4.0.6 on 2023-01-22 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_announcement', '0002_animal_announcment_remove_buttonquestion_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
