# Generated by Django 4.0.6 on 2023-01-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_announcement', '0004_alter_animal_care_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(max_length=10),
        ),
    ]
