# Generated by Django 4.0.6 on 2023-01-22 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_announcement', '0005_alter_animal_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='announcment',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='announcment',
            name='color',
        ),
        migrations.RemoveField(
            model_name='announcment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='announcment',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='announcment',
            name='health',
        ),
        migrations.RemoveField(
            model_name='announcment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='announcment',
            name='species',
        ),
        migrations.AddField(
            model_name='announcment',
            name='Animal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adoption_announcement.animal'),
        ),
    ]
