# Generated by Django 4.0.6 on 2023-01-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_announcement', '0006_remove_announcment_age_remove_announcment_breed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('Animal_Bio', models.TextField(default=' ', max_length=3000)),
                ('Animal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adoption_announcement.animal')),
            ],
        ),
        migrations.DeleteModel(
            name='Announcment',
        ),
    ]
