# Generated by Django 4.0.6 on 2023-01-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_announcement', '0008_announcement_added_by_alter_animal_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='care',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='health_and_vaccination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='past',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='Animal_Bio',
            field=models.TextField(blank=True),
        ),
    ]
