# Generated by Django 4.0.6 on 2023-01-28 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_announcement', '0009_alter_animal_care_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_education', models.CharField(max_length=250)),
                ('number_of_adults_in_the_house', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('number_of_children_in_the_house', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('other_animals', models.CharField(max_length=250)),
                ('hours_away_from_home', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('moving_out', models.CharField(max_length=250)),
                ('family_allergies', models.CharField(max_length=250)),
                ('adoption_reason', models.CharField(max_length=250)),
                ('animal_name', models.CharField(max_length=50)),
                ('availability', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('feeding_the_animal', models.CharField(max_length=250)),
                ('care_budget', models.CharField(max_length=150)),
                ('what_if_you_go_on_vacation', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='Animal_Bio',
            new_name='short_description',
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('Samiec', 'Samiec'), ('Samica', 'Samica'), ('Inna', 'Inna')], default='Inna', max_length=6),
        ),
    ]
