# Generated by Django 4.0.6 on 2023-01-26 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Numer telefonu musi zawierać prefix i nie może zawierać spacji', regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Zły format kodu pocztowego', regex='^[0-9]{6}$')]),
        ),
    ]
