# Generated by Django 4.0.6 on 2023-01-27 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_phone_number_alter_profile_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Zły format kodu pocztowego', regex='^[0-9]{5}$')]),
        ),
    ]
